Traceback (most recent call last):
  File "/Users/cyface/Dropbox/Personal/Cyface/Podiobooks/Aptana3Workspace/podiobooks/src/podiobooks/manage.py", line 14, in <module>
    execute_manager(settings)
  File "/Users/cyface/Dropbox/Personal/Cyface/Podiobooks/Aptana3Workspace/podiobooks/parts/podiobooks-test/django/core/management/__init__.py", line 438, in execute_manager
    utility.execute()
  File "/Users/cyface/Dropbox/Personal/Cyface/Podiobooks/Aptana3Workspace/podiobooks/parts/podiobooks-test/django/core/management/__init__.py", line 379, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/cyface/Dropbox/Personal/Cyface/Podiobooks/Aptana3Workspace/podiobooks/parts/podiobooks-test/django/core/management/base.py", line 191, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/Users/cyface/Dropbox/Personal/Cyface/Podiobooks/Aptana3Workspace/podiobooks/parts/podiobooks-test/django/core/management/base.py", line 220, in execute
    output = self.handle(*args, **options)
  File "/Users/cyface/Dropbox/Personal/Cyface/Podiobooks/Aptana3Workspace/podiobooks/parts/podiobooks-test/django/core/management/commands/dumpdata.py", line 84, in handle
    objects.extend(model._default_manager.using(using).all())
  File "/Users/cyface/Dropbox/Personal/Cyface/Podiobooks/Aptana3Workspace/podiobooks/parts/podiobooks-test/django/db/models/query.py", line 82, in __len__
    self._result_cache.extend(list(self._iter))
  File "/Users/cyface/Dropbox/Personal/Cyface/Podiobooks/Aptana3Workspace/podiobooks/parts/podiobooks-test/django/db/models/query.py", line 271, in iterator
    for row in compiler.results_iter():
  File "/Users/cyface/Dropbox/Personal/Cyface/Podiobooks/Aptana3Workspace/podiobooks/parts/podiobooks-test/django/db/models/sql/compiler.py", line 677, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/Users/cyface/Dropbox/Personal/Cyface/Podiobooks/Aptana3Workspace/podiobooks/parts/podiobooks-test/django/db/models/sql/compiler.py", line 732, in execute_sql
    cursor.execute(sql, params)
  File "/Users/cyface/Dropbox/Personal/Cyface/Podiobooks/Aptana3Workspace/podiobooks/parts/podiobooks-test/django/db/backends/util.py", line 15, in execute
    return self.cursor.execute(sql, params)
  File "/Users/cyface/Dropbox/Personal/Cyface/Podiobooks/Aptana3Workspace/podiobooks/parts/podiobooks-test/django/db/backends/postgresql_psycopg2/base.py", line 44, in execute
    return self.cursor.execute(query, args)
django.db.utils.DatabaseError: column main_titleurl.title_id does not exist
LINE 1: SELECT "main_titleurl"."id", "main_titleurl"."title_id", "ma...
                                     ^

